sudo: required
services: 
  - docker

before_install: 
  - docker build -t volodymyrholoida/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true -t volodymyrholoida/docker-react npm run test